### ISSUE TITLE
Some overlays are not working as they need to

### ISSUE THREAD

**Issue by ElfDecker** [andrewsarnold/FlagMaker-2#18]
So, some overlays, i.e. saltire, triangle, pall, quadrilateral and rays are not rendering as intended. Trying to render them just give me some strange triangles instead of rays, palls and so on.

**Comment by andrewsarnold** [comment]
Can you post a screenshot of what you're seeing? Is this during regular display, or when you export to an image? What's your operating system and configuration?

**Comment by ElfDecker** [comment]
I will post it with examples of your own prescripted flags.
![image](https://user-images.githubusercontent.com/5684686/28528539-a904d834-7096-11e7-8738-0ec40f19552e.png)
Japan

![image](https://user-images.githubusercontent.com/5684686/28528559-be229a6c-7096-11e7-87fc-569d0035b4e3.png)
Palestine

My OS is Windows 10.

**Comment by andrewsarnold** [comment]
@ElfDecker Hey I think I have a fix for this — I am pretty sure it's because you're using a language on your computer that uses "," instead of "." for decimal points. I just checked in change https://github.com/andrewsarnold/FlagMaker-2/commit/b4b6b22409c9b6e832aea39bd356500c5411d9ec that should fix it. Are you able to test it on your computer?

**Comment by TheIntelG** [comment]
@andrewsarnold Hi, I'm having the same issue as ElfDecker, I'm using Windows 8 and even if i use a language on my computer that uses "." that bug still happens.
